org.gradle.jvmargs=-Xmx3072M -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
kotlin.compiler.execution.strategy=in-process
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

